fn main() {
    // 错误分为两类 一种是可恢复错误 一种是不可恢复错误
    
}
